name: "scan2html"
repository: github.com/afdesk/scan2html
version: "0.0.4"
usage: scan targets into a html file
description: |-
  A Trivy plugin that scans and outputs the results to a html file.
  trivy scan2html [-h,--help] command target filename
platforms:
  -
    uri: https://github.com/afdesk/scan2html/releases/download/v0.0.4/scan2html.tar.gz
    bin: ./scan2html
