#!/bin/bash

# help
function help() {
  cat <<EOS >&2
scan2html v__VERSION__

Usage: trivy scan2html [-h,--help] command target filename
 A Trivy plugin that scans and output the results to a html file.
Options:
  -h, --help    Show usage.
Examples:
  # Scan $(alpine:latest) image
  trivy scan2html image alpine:latest result.html

  # Scan local folder
  trivy scan2html fs . result.html
EOS
  exit
}

function scan {
  BASEDIR=$(dirname "$0")
  args=("${@:2:$#-2}")
  last_arg="${!#}"
  set -- "$1" "${args[@]}" "$last_arg"
  trivy $1 --format json -o $BASEDIR/data.js ${args[@]}
  cat $BASEDIR/first.html >$last_arg
  echo "const trivyData = " >>$last_arg
  cat $BASEDIR/data.js >>$last_arg
  echo "const createdAt = $(date +%s%3N)" >>$last_arg
  cat $BASEDIR/second.html >>$last_arg
}

if [[ ($# -eq 0) || ($1 == "--help") || ($1 == "-h") ]]; then
  help
fi

scan "$@"
