name: Release

on:
  push:
    branches:
      - main
    paths:
      - "plugin.yaml"

permissions:
  contents: write

jobs:
  check-version:
    uses: afdesk/trivy-go-plugin/.github/workflows/check-version.yaml@main

  build:
    name: "Build application"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs: check-version
    if: ${{ needs.check-version.outputs.next_version != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3


  release:
    needs: check-version
    uses: afdesk/trivy-go-plugin/.github/workflows/release-go.yaml@main
    with:
      next-version: '${{ needs.check-version.outputs.next-version }}'
