name: Test
on:
  push:
  pull_request:
    branches:
      - '**'
env:
  GO_VERSION: '1.23.3'

jobs:
  unittest:
    runs-on: ubuntu-22.04
    name: Test
    steps:

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Go mod tidy
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain)" ]; then
            echo "Run 'go mod tidy' and push it"
            exit 1
          fi

      - name: Run unit tests
        run: go test -v -short -timeout 30s -coverprofile=coverage.txt -covermode=atomic ./...

